### ISSUE TITLE
Bug: Intermittent corrupt ion image files causing processing to fail

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#682]
This bug manifests during colocalization, when all first-isotope ion images are read back, after the main annotation has successfully completed. This error causes the dataset to fail before indexing, meaning the user gets an email saying it failed and the results are never accessible. The bug seems to be random - datasets will usually succeed if reprocessed, even if nothing is changed.

Stack trace of error:
```
Traceback (most recent call last):
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/sm_daemons.py", line 266, in _callback
    ds=ds, annotation_job_factory=AnnotationJob, del_first=msg.get('del_first', False)
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/sm_daemons.py", line 97, in annotate
    Colocalization(self._db, self._img_store).run_coloc_job(ds.id, reprocess=del_first)
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/colocalization.py", line 407, in run_coloc_job
    ds_id, moldb_id, image_storage_type, charge
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/colocalization.py", line 378, in _get_existing_ds_annotations
    image_storage_type, image_ids
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/png_generator.py", line 166, in get_ion_images_for_analysis
    for _ in executor.map(process_img, img_ids[1:], range(1, len(img_ids))):
  File "/opt/dev/miniconda3/envs/sm/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/opt/dev/miniconda3/envs/sm/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/dev/miniconda3/envs/sm/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/dev/miniconda3/envs/sm/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/png_generator.py", line 140, in process_img
    img = self.get_image_by_id(storage_type, 'iso_image', img_id)
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/util.py", line 193, in wrapper
    return func(*args, **kwargs)
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/png_generator.py", line 80, in get_image_by_id
    return Image.open(BytesIO(response.content))
  File "/opt/dev/miniconda3/envs/sm/lib/python3.6/site-packages/PIL/Image.py", line 2931, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fc8ae170308>
```

Although the error occurs during download, the issue is actually caused some time during upload of the images. Somehow the ion images are saved as empty files (0 bytes).

e.g. ion image `a521bad691f920ff4d98d4080f97404d` (`C48H94NO7P+K` first ion image) from failed dataset `2020-09-03_09h05m00s`. This ion image shouldn't be empty - according to the intensity data, all 4 peaks should have had at least 100 pixels present. The annotation got an MSM score of 0.362 and FDR of 50%.

First observed: 2020-08-30
Deployment history before first observance:
* 2020-08-28: bc29c8a
* 2020-08-10: 68217d9
* 2020-07-29: ecab3ba
* 2020-07-29: bf1d5aa

**Comment by LachlanStuart** [comment]
This error has not happened again since #683 was deployed. Looks fixed to me :+1:
